Feat/user context
Reciclarte-Kenzie/reciclarte pull request #10
Opened 2023-01-04 18:33 UTC by freitassneto

2023-01-04 20:14 UTC, Danielle-Luz requested changes
- As requisições GET precisam retornar os dados que foram obtidos, as funções estão apenas fazendo as requisições, sem retornar nada
- Como as funções passaram a retornar algo, a tipagem das funções no `iUserContextProvider` precisa mudar.
- O PATCH precisa receber como argumento apenas a rota e os dados que serão atualizados, não é preciso do JSON.stringify na linha 100, o próprio axios já se encarrega de converter em json.
- Os headers que possuem apenas a propriedade content-type são desnecessários, é melhor informar os headers apenas nas requests que precisam de token.
- Ao invés de repetir os headers com o token em cada requisição que precisa do token, é melhor guardar esse objeto numa constante dentro do provider e passá-la como argumento sempre que necessário para a requisição.
- Já havia uma pasta para o UserProvider, o nome dela é providers, seria interessante mudar o arquivo para essa pasta ao invés de deixá-lo na pasta context.
- Um nome mais adequado para o arquivo userContext seria UserProvider, seguindo um padrão.

2023-01-05 14:45 UTC, tulio-albuquerque commented
O delete podia estar deslogando o usuário mas isso pode ser feito em um fix depois

2023-01-05 14:49 UTC, tulio-albuquerque commented
O state com o usuário só esta guardando o token ? eu sempre guardei tudo o que o vem com a requisição do login

2023-01-05 14:52 UTC, Danielle-Luz approved these changes

2023-01-05 15:23 UTC, Danielle-Luz approved these changes

2023-01-05 15:24 UTC, merged

2023-01-05 15:25 UTC, tulio-albuquerque approved these changes