feat Routes
Reciclarte-Kenzie/reciclarte pull request #3
Opened 2023-01-03 22:23 UTC by CarolinaOlivaCruz

2023-01-03 23:33 UTC, Danielle-Luz requested changes
Carol, acho que seria interessante fazer algumas mudanças antes do merge:

1. Inserir o `<BrowserRouter>` dentro do componente `App` ao invés de estar diretamente na função `render`.
2. Inserir uma rota com path `*` redirecionando para a homepage por meio de um componente `Navigate`, por exemplo: `<Route path="*" element={<Navigate to="/" />} />`

2023-01-04 13:10 UTC, Danielle-Luz approved these changes

2023-01-04 13:26 UTC, tulio-albuquerque commented
Por que as rotas estão comentadas ?

2023-01-04 13:38 UTC, CarolinaOlivaCruz commented
As rotas estão comentadas porque fica com erro visto que não tem componente

2023-01-04 13:54 UTC, tulio-albuquerque approved these changes

2023-01-04 14:15 UTC, Danielle-Luz approved these changes

2023-01-04 14:16 UTC, merged