Feat/profile page
Reciclarte-Kenzie/reciclarte pull request #54
Opened 2023-01-10 21:18 UTC by tulio-albuquerque

2023-01-10 21:27 UTC, CToH10 requested changes
os outros feedbacks se mantém
a API retorna lista vazia caso não exista ideia, então só verificar se existe não é suficiente pra saber se o usuário tem ideia cadastrada

2023-01-10 22:11 UTC, Danielle-Luz requested changes
- Ao recarregar a página o login some, provavelmente o estado do usuário é limpo e as informações deixam de estar disponíveis.
- O styled component StyledContainer dentro da pasta styles podia ser usado no header e em volta da lista de ideias.

2023-01-11 01:16 UTC, tulio-albuquerque commented
@Danielle-Luz Vou dar uma olhada no StyledContainer mas o login some por falta do autologin, isso seria uma alteração no Provider do contexto do usuário

2023-01-11 01:54 UTC, tulio-albuquerque commented
O StyledContainer esta sendo sobrescrito na pagina home, teria que ter uma refatoração para evitar inconsistência entre as paginas

2023-01-11 03:46 UTC, Danielle-Luz requested changes
- Use as variáveis de cor e de tamanho de fonte que estão no global styles ao invés de inserir seus valores diretamente, como todos fizeram isso, também é importante fazer pra manter o padrão de código.
- Remova os comentários no código CSS e os console.log usados pra debugar.

2023-01-11 03:53 UTC, Danielle-Luz commented
> O StyledContainer esta sendo sobrescrito na pagina home, teria que ter uma refatoração para evitar inconsistência entre as paginas

Fiz uma branch alternativa que até coloquei no grupo do slack, lá eu integrei o ContainerStyled na homepage, assim como no header, [essa é a branch](https://github.com/Reciclarte-Kenzie/reciclarte/tree/feat/change-home-sizes), pedi que vcs dessem uma olhada e opinassem. O Luís e a Carol já sinalizaram positivamente.

Ele também não é sobrescrito na develop, a carol criou outro componente. Até preservei algumas das particularidades desse componente criado por ela nessa branch, mas a base do StyledContainer da homepage passa a ser o ContainerStyled, uso ele na linha 4 [no styles da home](https://github.com/Reciclarte-Kenzie/reciclarte/blob/feat/change-home-sizes/src/pages/home/styles.ts) e na linha 12 do [styles do header](https://github.com/Reciclarte-Kenzie/reciclarte/blob/feat/change-home-sizes/src/components/Header/styles.ts).

2023-01-11 18:43 UTC, CToH10 requested changes
Nos estilos do header alguns font sizes ainda não tão usando as variáveis
Os botões do card de perfil estão transparentes, são renderizados, mas não estão visíveis
Mesmo depois de eu reiniciar a aplicação (tentei o F5 e ctrl+F5 também) o header está se comportando como se sempre tivesse usuário logado, até com o localStorage limpo
O botão de logout não está funcional

2023-01-11 22:29 UTC, merged